# Generated by Django 4.2.13 on 2026-04-04 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='responding_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
