# Generated by Django 4.2.13 on 2026-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0002_sosalert_responders'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
