# Generated by Django 4.2.13 on 2026-05-06 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complains', '0004_legalaidapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalaidapplication',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='responding_to_aid', to=settings.AUTH_USER_MODEL),
        ),
    ]
