# Generated by Django 4.2.27 on 2026-05-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('complains', '0005_legalaidapplication_responders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_resolved_user', models.BooleanField(default=False)),
                ('user_review', models.TextField(blank=True, null=True)),
                ('is_resolved_responder', models.BooleanField(default=False)),
                ('responder_review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Resolve Statuses',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='complains_r_content_96051c_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
