# Generated by Django 4.2.13 on 2026-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complains', '0006_resolvestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvestatus',
            name='responder_submitted_resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resolvestatus',
            name='user_submitted_resolve',
            field=models.BooleanField(default=False),
        ),
    ]
