version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: nirbhoy-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: nirbhoy-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: nirbhoy-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8H27GO4GC722
      POSTGRES_DB: nirbhoy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nirbhoy-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nirbhoy.com
      PGADMIN_DEFAULT_PASSWORD: K5ZI6613LM7U
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data: