# Generated by Django 4.2.13 on 2026-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
