# Generated by Django 4.2.13 on 2026-05-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
