# Generated by Django 4.2.13 on 2026-05-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
