# Generated by Django 4.2.13 on 2026-05-04 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyerprofile_bar_council_id_image_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bar_council_id_image',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='nid_image',
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='bar_council_id_file',
            field=models.FileField(blank=True, null=True, upload_to='lawyer_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
