# Generated by Django 4.2.13 on 2026-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_lawyerprofile_bar_council_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bar_council_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
