# Generated by Django 4.2.27 on 2026-05-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lawyerprofile_created_at_lawyerprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_anonymous_user',
        ),
    ]
